<?php
/**
 * MailPilot web installer. Run once, then delete this file.
 */
define('EMT', 1);
require __DIR__ . '/app/bootstrap.php';

$h = 'Util::h';
$errors = array();
$done = false;
$manualConfig = null;

$checks = array(
    array('PHP 7.4 or newer', version_compare(PHP_VERSION, '7.4.0', '>='), 'You have PHP ' . PHP_VERSION . '. Choose a newer version in cPanel → Select PHP Version.'),
    array('PDO MySQL extension', extension_loaded('pdo_mysql'), 'Enable "pdo_mysql" in cPanel → Select PHP Version → Extensions.'),
    array('OpenSSL extension', extension_loaded('openssl'), 'Enable "openssl" in cPanel → Select PHP Version → Extensions.'),
    array('mbstring extension', extension_loaded('mbstring'), 'Recommended: enable "mbstring" in cPanel → Select PHP Version → Extensions.'),
    array('app/ folder is writable', is_writable(EMT_APP), 'Set the permissions of the "app" folder to 755 (File Manager → Permissions).'),
    array('storage/ folder is writable', is_dir(EMT_STORAGE) && is_writable(EMT_STORAGE), 'Create the "storage" folder and set its permissions to 755.'),
);
$blocking = !$checks[0][1] || !$checks[1][1] || !$checks[2][1] || !$checks[5][1];

$form = array(
    'db_host' => 'localhost',
    'db_port' => '3306',
    'db_name' => '',
    'db_user' => '',
    'db_pass' => '',
    'app_url' => rtrim(Util::guessBaseUrl(), '/'),
    'admin_user' => Schema::DEFAULT_ADMIN_USER,
    'admin_pass' => '',
    'timezone' => 'UTC',
);

if (!emt_installed() && $_SERVER['REQUEST_METHOD'] === 'POST' && !$blocking) {
    foreach ($form as $k => $v) {
        if (isset($_POST[$k]) && is_string($_POST[$k])) {
            $form[$k] = $k === 'db_pass' || $k === 'admin_pass' ? $_POST[$k] : trim($_POST[$k]);
        }
    }
    if ($form['db_name'] === '' || $form['db_user'] === '') {
        $errors[] = 'Enter the database name and database user.';
    }
    if (!preg_match('#^https?://#i', $form['app_url'])) {
        $errors[] = 'The app URL must start with https:// (for example https://marketing.dauddev.com).';
    }
    if ($form['admin_pass'] !== '' && strlen($form['admin_pass']) < 8) {
        $errors[] = 'The admin password must be at least 8 characters (or leave it empty to keep the pre-configured one).';
    }
    if (!preg_match('/^[A-Za-z0-9_.@-]{3,64}$/', $form['admin_user'])) {
        $errors[] = 'The admin username must be 3-64 characters (letters, numbers, . _ - @).';
    }
    if (!in_array($form['timezone'], timezone_identifiers_list(), true)) {
        $form['timezone'] = 'UTC';
    }
    if (!$errors) {
        $db = array(
            'host' => $form['db_host'] ?: 'localhost',
            'port' => (int) $form['db_port'] ?: 3306,
            'name' => $form['db_name'],
            'user' => $form['db_user'],
            'pass' => $form['db_pass'],
        );
        try {
            $pdo = DB::connect($db);
            DB::setPdo($pdo);
        } catch (PDOException $e) {
            $errors[] = 'Could not connect to the database: ' . $e->getMessage();
        }
    }
    if (!$errors) {
        $config = array(
            'db' => $db,
            'app_key' => Util::randomHex(32),
            'cron_key' => Util::randomHex(16),
        );
        $php = "<?php\n// MailPilot configuration — generated by install.php on " . gmdate('Y-m-d H:i') . " UTC.\n"
            . "// Keep this file private. Never share app_key.\n"
            . "defined('EMT') or exit;\n\nreturn " . var_export($config, true) . ";\n";
        $written = @file_put_contents(EMT_CONFIG, $php, LOCK_EX) !== false;
        if (!$written) {
            $manualConfig = $php;
        }
        try {
            // Make the fresh config visible to the helpers used below.
            if ($written) {
                @chmod(EMT_CONFIG, 0640);
                if (function_exists('opcache_invalidate')) {
                    @opcache_invalidate(EMT_CONFIG, true);
                }
            }
            Schema::install($form['admin_user'], $form['admin_pass']);
            DB::q('INSERT INTO emt_settings (k, v) VALUES (?, ?), (?, ?) ON DUPLICATE KEY UPDATE v = VALUES(v)', array(
                'app_url', rtrim($form['app_url'], '/'), 'timezone', $form['timezone'],
            ));
            $done = true;
        } catch (Exception $e) {
            $errors[] = 'Database setup failed: ' . $e->getMessage();
            if ($written) {
                @unlink(EMT_CONFIG);
            }
            $manualConfig = null;
        }
    }
}
header('Content-Type: text/html; charset=utf-8');
header('X-Robots-Tag: noindex');
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Install MailPilot</title>
<link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
<style>
  :root { --bg:#f3f4fb; --card:#fff; --text:#161827; --muted:#687087; --primary:#5b5bf0; --primary2:#8b5cf6; --border:#e4e6f0; --ok:#12b76a; --bad:#f04438; --warn:#f79009; }
  * { box-sizing:border-box; }
  body { margin:0; font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; background:var(--bg); color:var(--text); min-height:100vh; }
  .bg { position:fixed; inset:0; overflow:hidden; z-index:-1; }
  .bg span { position:absolute; border-radius:50%; filter:blur(80px); opacity:.45; animation:float 18s ease-in-out infinite; }
  .bg span:nth-child(1){ width:480px; height:480px; background:#a5b4fc; top:-120px; left:-100px; }
  .bg span:nth-child(2){ width:420px; height:420px; background:#f0abfc; bottom:-140px; right:-80px; animation-delay:-6s; }
  @keyframes float { 50% { transform:translate(40px,30px) scale(1.08); } }
  .wrap { max-width:640px; margin:0 auto; padding:48px 16px; }
  .brand { display:flex; align-items:center; gap:12px; font-weight:800; font-size:22px; margin-bottom:24px; }
  .logo { width:42px; height:42px; border-radius:12px; background:linear-gradient(135deg,var(--primary),var(--primary2)); display:grid; place-items:center; box-shadow:0 10px 24px -10px var(--primary); }
  .card { background:var(--card); border:1px solid var(--border); border-radius:20px; padding:28px; box-shadow:0 24px 60px -30px rgba(40,40,100,.3); margin-bottom:18px; animation:up .5s ease both; }
  @keyframes up { from { opacity:0; transform:translateY(14px);} to { opacity:1; transform:none; } }
  h1 { margin:0 0 6px; font-size:24px; } h2 { font-size:16px; margin:0 0 14px; }
  p.lead { color:var(--muted); margin:0 0 20px; line-height:1.6; }
  .checks { list-style:none; padding:0; margin:0; display:grid; gap:8px; }
  .checks li { display:flex; gap:10px; align-items:flex-start; font-size:14px; }
  .dot { width:20px; height:20px; border-radius:50%; flex:none; display:grid; place-items:center; color:#fff; font-size:12px; font-weight:700; }
  .ok { background:var(--ok); } .bad { background:var(--bad); } .warn { background:var(--warn); }
  .hint { color:var(--muted); font-size:12.5px; display:block; }
  .grid { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
  .full { grid-column:1/-1; }
  label { font-size:13px; font-weight:600; display:block; margin-bottom:6px; }
  input, select { width:100%; border:1px solid var(--border); border-radius:11px; padding:11px 13px; font-size:14.5px; font-family:inherit; background:#fbfbfe; color:var(--text); transition:border .15s, box-shadow .15s; }
  input:focus, select:focus { outline:none; border-color:var(--primary); box-shadow:0 0 0 4px rgba(91,91,240,.15); background:#fff; }
  .section { font-size:12px; text-transform:uppercase; letter-spacing:.08em; color:var(--muted); font-weight:700; margin:22px 0 12px; grid-column:1/-1; }
  button { margin-top:22px; width:100%; border:0; border-radius:12px; padding:14px; font-size:15px; font-weight:700; color:#fff; cursor:pointer;
           background:linear-gradient(135deg,var(--primary),var(--primary2)); box-shadow:0 12px 28px -12px var(--primary); transition:transform .15s; }
  button:hover { transform:translateY(-1px); }
  .alert { border-radius:12px; padding:12px 14px; font-size:14px; margin-bottom:16px; line-height:1.5; }
  .alert.err { background:#fef3f2; color:#b42318; border:1px solid #fecdca; }
  .alert.okk { background:#ecfdf3; color:#067647; border:1px solid #abefc6; }
  pre { background:#0f1020; color:#d6d8ff; padding:14px; border-radius:12px; overflow:auto; font-size:12.5px; }
  a.btn { display:inline-block; margin-top:10px; text-decoration:none; color:#fff; background:linear-gradient(135deg,var(--primary),var(--primary2)); padding:13px 22px; border-radius:12px; font-weight:700; }
  @media (max-width:560px) { .grid { grid-template-columns:1fr; } }
</style>
</head>
<body>
<div class="bg"><span></span><span></span></div>
<div class="wrap">
  <div class="brand"><div class="logo"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 2 11 13"/><path d="M22 2 15 22l-4-9-9-4 20-7z"/></svg></div>MailPilot</div>

<?php if (emt_installed() && !$done): ?>
  <div class="card">
    <h1>Already installed ✅</h1>
    <p class="lead">MailPilot is installed. For security, <b>delete install.php</b> from your server now.</p>
    <a class="btn" href="./">Open MailPilot →</a>
  </div>
<?php elseif ($done): ?>
  <div class="card">
    <h1>Installation complete 🎉</h1>
    <?php if ($manualConfig): ?>
      <div class="alert err">The installer could not write <b>app/config.php</b>. Create that file yourself (File Manager → app → + File → config.php) and paste this content into it:</div>
      <pre><?php echo $h($manualConfig); ?></pre>
    <?php else: ?>
      <div class="alert okk">Database tables were created and your configuration was saved.</div>
    <?php endif; ?>
    <p class="lead">
      Sign in with username <b><?php echo $h($form['admin_user']); ?></b> and <?php echo $form['admin_pass'] !== '' ? 'the password you just chose' : 'your pre-configured password'; ?>.<br>
      <b>Important:</b> delete <code>install.php</code> from the server now, then continue with the cron job setup from the guide.
    </p>
    <a class="btn" href="./">Open MailPilot →</a>
  </div>
<?php else: ?>
  <div class="card">
    <h1>Install MailPilot</h1>
    <p class="lead">This takes one minute. Create a MySQL database + user in cPanel first (see the guide), then fill in the form.</p>
    <h2>Server check</h2>
    <ul class="checks">
      <?php foreach ($checks as $i => $c): ?>
        <li><span class="dot <?php echo $c[1] ? 'ok' : ($i === 3 || $i === 4 ? 'warn' : 'bad'); ?>"><?php echo $c[1] ? '✓' : '!'; ?></span>
          <span><?php echo $h($c[0]); ?><?php if (!$c[1]): ?><span class="hint"><?php echo $h($c[2]); ?></span><?php endif; ?></span></li>
      <?php endforeach; ?>
    </ul>
  </div>

  <form class="card" method="post" autocomplete="off">
    <?php foreach ($errors as $e): ?><div class="alert err"><?php echo $h($e); ?></div><?php endforeach; ?>
    <div class="grid">
      <div class="section">Database</div>
      <div><label>Database host</label><input name="db_host" value="<?php echo $h($form['db_host']); ?>"></div>
      <div><label>Port</label><input name="db_port" value="<?php echo $h($form['db_port']); ?>"></div>
      <div class="full"><label>Database name</label><input name="db_name" value="<?php echo $h($form['db_name']); ?>" placeholder="e.g. cpuser_mailpilot" required></div>
      <div><label>Database user</label><input name="db_user" value="<?php echo $h($form['db_user']); ?>" placeholder="e.g. cpuser_mpuser" required></div>
      <div><label>Database password</label><input type="password" name="db_pass" value="<?php echo $h($form['db_pass']); ?>"></div>

      <div class="section">Application</div>
      <div class="full"><label>App URL</label><input name="app_url" value="<?php echo $h($form['app_url']); ?>" placeholder="https://marketing.dauddev.com"></div>
      <div class="full"><label>Timezone</label>
        <select name="timezone" id="tz">
          <?php foreach (timezone_identifiers_list() as $tz): ?>
            <option value="<?php echo $h($tz); ?>"<?php echo $tz === $form['timezone'] ? ' selected' : ''; ?>><?php echo $h($tz); ?></option>
          <?php endforeach; ?>
        </select>
      </div>

      <div class="section">Admin account</div>
      <div><label>Username</label><input name="admin_user" value="<?php echo $h($form['admin_user']); ?>"></div>
      <div><label>Password</label><input type="password" name="admin_pass" placeholder="Leave empty = pre-configured"><span class="hint">Leave empty to use the pre-configured password.</span></div>
    </div>
    <button type="submit"<?php echo $blocking ? ' disabled style="opacity:.5;cursor:not-allowed"' : ''; ?>>Install MailPilot</button>
  </form>
<?php endif; ?>
</div>
<script>
  (function () {
    var sel = document.getElementById('tz');
    if (!sel || sel.value !== 'UTC') return;
    try {
      var tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
      if (tz) { for (var i = 0; i < sel.options.length; i++) if (sel.options[i].value === tz) { sel.value = tz; break; } }
    } catch (e) {}
  })();
</script>
</body>
</html>
